// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ePizza.Infrastructure.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ePizza.Infrastructure.Entities
{
    public partial class ePizzaDbContext
    {
        private IePizzaDbContextProcedures _procedures;

        public virtual IePizzaDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ePizzaDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IePizzaDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class ePizzaDbContextProcedures : IePizzaDbContextProcedures
    {
        private readonly ePizzaDbContext _context;

        public ePizzaDbContextProcedures(ePizzaDbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<usp_fetchpaymentDetailsResult>> usp_fetchpaymentDetailsAsync(string paymentId, OutputParameter<int> returnValue = null,
            CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PaymentId",
                    Size = -1,
                    Value = paymentId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };

            // this line of code will call the stored procedure using EF core and these code are generated by EF core power tools.
            var _ = await _context.SqlQueryAsync<usp_fetchpaymentDetailsResult>("EXEC @returnValue = [dbo].[usp_fetchpaymentDetails] @PaymentId = @PaymentId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
