// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ePizza.Infrastructure.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ePizza.Infrastructure.Entities
{
    public partial interface IePizzaDbContextProcedures
    {
        Task<List<usp_fetchpaymentDetailsResult>> usp_fetchpaymentDetailsAsync(string paymentId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
