// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ePizza.Infrastructure.Entities
{
    public partial class usp_fetchpaymentDetailsResult
    {
        public Guid CartId { get; set; }
        [StringLength(2147483647)]
        public string Currency { get; set; }
        [Column("Total", TypeName = "decimal(18,2)")]
        public decimal Total { get; set; }
        [Column("Tax", TypeName = "decimal(18,2)")]
        public decimal Tax { get; set; }
        [Column("GrandTotal", TypeName = "decimal(18,2)")]
        public decimal GrandTotal { get; set; }
    }
}
